version: '2.4'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.9.3
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      # java heap大小
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300

  elasticsearch02:
    container_name: elasticsearch02
    image: elasticsearch:7.9.3
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    container_name: kibana
    image: kibana:7.9.3
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    container_name: logstash
    build: ./logstash
    ports:
      - 9600:9600
    depends_on:
      - elasticsearch
    external_links:
      - mysql:mysql
    volumes:
      - ./logstash/config:/usr/share/logstash/config
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - default
      - mysqlnet

# 使用外部已有网络，连接mysql；如果mysql不使用docker，logstash-mysql.conf的mysql连接就行了
networks:
  mysqlnet:
    external:
      name: docker-lnmp_code-network